
import React from "react";
import { Card, CardHeader, CardTitle, CardContent } from "../../ui/card";

const HeliumProductionSection: React.FC = () => (
  <Card className="my-4 border border-yellow-200 dark:border-yellow-700">
    <CardHeader className="bg-yellow-50 dark:bg-gray-800 p-4">
      <CardTitle className="text-lg">Production &amp; Synthesis</CardTitle>
    </CardHeader>
    <CardContent className="p-4 text-xs">
      <div className="space-y-2">
        <div>
          <strong>Natural production:</strong> On Earth, almost all helium is generated by alpha decay of heavy radioactive minerals (e.g., uranium, thorium), accumulating in natural gas reservoirs.
        </div>
        <div>
          <strong>Extraction process:</strong>
          <ul className="list-disc pl-4 space-y-1">
            <li>Helium is extracted as a byproduct of natural gas processing (natural gas containing up to 8% He).</li>
            <li>Methods: cryogenic distillation and pressure swing adsorption separate helium from other gases due to its very low boiling point (4.2 K).</li>
            <li>Final purification yields “Grade A” (99.99%+) helium.</li>
          </ul>
        </div>
        <div>
          <strong>Atmospheric helium:</strong> Not economically viable to extract from air due to extremely low concentration.
        </div>
        <div>
          <strong>Global production:</strong> About 160 million cubic meters produced annually (as of 2022).
        </div>
      </div>
      <div className="mt-2 text-[11px] text-gray-500">
        Sources: USGS Mineral Commodity Summaries, Air Liquide, Royal Society of Chemistry, IUPAC
      </div>
    </CardContent>
  </Card>
);

export default HeliumProductionSection;
